package it.alessandromodica.giococarte.model.po;
// Generated 8-ago-2018 10.06.25 by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PluginGestioneApps generated by hbm2java
 */
@Entity
public class GestioneApps implements java.io.Serializable {

	private int idapp;
	private Integer idutente;
	private Date istante;
	private String tokenapp;

	public GestioneApps() {
	}

	public GestioneApps(int idapp, Date istante) {
		this.idapp = idapp;
		this.istante = istante;
	}

	public GestioneApps(int idapp, Integer idutente, Date istante, String tokenapp) {
		this.idapp = idapp;
		this.idutente = idutente;
		this.istante = istante;
		this.tokenapp = tokenapp;
	}

	@Id

	@Column(name = "idapp", unique = true, nullable = false)
	public int getIdapp() {
		return this.idapp;
	}

	public void setIdapp(int idapp) {
		this.idapp = idapp;
	}

	@Column(name = "idutente")
	public Integer getIdutente() {
		return this.idutente;
	}

	public void setIdutente(Integer idutente) {
		this.idutente = idutente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "istante", nullable = false, length = 19)
	public Date getIstante() {
		return this.istante;
	}

	public void setIstante(Date istante) {
		this.istante = istante;
	}

	@Column(name = "tokenapp", length = 256)
	public String getTokenapp() {
		return this.tokenapp;
	}

	public void setTokenapp(String tokenapp) {
		this.tokenapp = tokenapp;
	}

}
